name: build iOS app

on:
  workflow_dispatch:

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      # this was more debug as was curious what came pre-installed
      # GitHub shares this online, e.g. https://github.com/actions/runner-images/blob/macOS-12/20230224.1/images/macos/macos-12-Readme.md
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Install the Apple distribution certificate
        env:
          APPLE_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_BASE64 }}
          APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          DISTRIBUTION_CERTIFICATE_PATH=distribution_certificate.p12
          KEYCHAIN_PATH=app-signing.keychain-db

          # decoding password
          APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD=$(echo -n "$APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD_BASE64" | base64 --decode)

          # import certificate from secrets
          echo -n "$APPLE_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode -o $DISTRIBUTION_CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security default-keychain -d user -s $KEYCHAIN_PATH

          # import certificate to keychain
          security import $DISTRIBUTION_CERTIFICATE_PATH -P "$APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH -T "/usr/bin/codesign"
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          security find-identity -v -p codesigning

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyjwt cryptography requests
      
      - name: Download provisioning profile
        env:
          APPLE_CONNECT_API_KEY_BASE64: ${{ secrets.APPLE_CONNECT_API_KEY_BASE64 }}
          APPLE_CONNECT_PRIVATE_KEY_ISSUER_ID_BASE64: ${{ secrets.APPLE_CONNECT_PRIVATE_KEY_ISSUER_ID_BASE64 }}
          APPLE_CONNECT_PRIVATE_KEY_BASE64: ${{ secrets.APPLE_CONNECT_PRIVATE_KEY_BASE64 }}
          PROVISIONING_PROFILE_ID_BASE64: ${{ secrets.PROVISIONING_PROFILE_ID_BASE64 }}
        run: |
          python3 download_provisioning_profile.py
          ls provisioning_profile.mobileprovision

          # apply provisioning profile
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp ./provisioning_profile.mobileprovision ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles

          # cp provisioning profile into two places to make sure it works
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Checkout PhotoAlbumKMP repo to a directory
        uses: actions/checkout@v2
        with:
          repository: AungThiha/PhotoAlbumKMP
          path: ./PhotoAlbumKMP  # This will clone it into the "PhotoAlbumKMP" directory

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build archive
        run: |
          cd ./PhotoAlbumKMP/iosApp

          xcodebuild -project ./iosApp.xcodeproj \
          -scheme iosApp -configuration "Release" \
          -allowProvisioningUpdates \
          -destination generic/platform=iOS \
          -archivePath ./build/iosApp.xcarchive \
          archive         

      - name: Export ipa
        env:
          EXPORT_OPTIONS_PLIST_BASE64: ${{ secrets.EXPORT_OPTIONS_PLIST_BASE64 }}
        run: |

          cd ./PhotoAlbumKMP/iosApp

          EXPORT_OPTS_PATH=ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST_BASE64" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/iamgroot.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build          

          xcodebuild -exportArchive \
          -archivePath ./build/iosApp.xcarchive \
          -exportPath ./build/ipa \
          -exportOptionsPlist ExportOptions.plist

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./PhotoAlbumKMP/iosApp/build/ipa/PhotoAlbum.ipa
          retention-days: 3